[package]
name = "mammut"
version = "0.8.0"
description = "A wrapper around the Mastodon API."
authors = ["Aaron Power <theaaronepower@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/Aaronepower/mammut.git"
keywords = ["api", "web", "social", "mastodon", "wrapper"]
categories = ["web-programming", "http-client"]

[dependencies]
reqwest = "0.6"
serde = "1"
serde_json = "1"
serde_derive = "1"
url = "1.5"

[dependencies.chrono]
# Locked to 0.3.0 since chrono 0.3.1 uses serde ^1, which is incompatible
# with serde 0.9 specified above.
version = "0.3"
features = ["serde"]
